name: CMORE SIBS e2e Test

on:
  workflow_dispatch:

jobs:
  cypress-e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: e2e Test on Chrome
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          headed: true

      - name: Uploading e2e artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-e2e-report
          path: cypress/reports/html
          retention-days: 7

  cypress-load-10:
    runs-on: ubuntu-latest
    needs: cypress-e2e
    if: always()
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Run 10 parallel load simulation
        run: npm run load:10

      - name: Uploading load artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-load-10-report
          path: |
            cypress/reports/html
            cypress/screenshots
            cypress/videos
          retention-days: 7