name: CMORE SIBS Tests

on:
  workflow_dispatch:
    inputs:
      test_type:
        description: "Select test type"
        required: true
        default: "e2e"
        type: choice
        options:
          - e2e
          - load-3
          - load-6
          - load-10

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Run E2E Tests
        if: github.event.inputs.test_type == 'e2e'
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          headed: true

      - name: Run Load Test 3 Users
        if: github.event.inputs.test_type == 'load-3'
        run: npm run load:3

      - name: Run Load Test 6 Users
        if: github.event.inputs.test_type == 'load-6'
        run: npm run load:6

      - name: Run Load Test 10 Users
        if: github.event.inputs.test_type == 'load-10'
        run: npm run load:10

      - name: Uploading artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-execution-report-${{ github.event.inputs.test_type }}
          path: |
            cypress/reports/html
            cypress/screenshots
            cypress/videos
          retention-days: 7